V4 - Additional improvements
spatie/laravel-activitylog pull request #872
Opened 2021-04-22 11:33 UTC by nagi1

- [x] Add docblock for some undocumented public functions.
- [x] Add ability to get batch uuid in `LogBatch::withinBatch()`.
- [x] Add ability to compare date intervals casts.

2021-04-22 12:48 UTC, Gummibeer requested changes

2021-04-22 12:48 UTC, Gummibeer commented on src/Traits/LogsActivity.php
> +                    // Handels Date intervels comparsons since php cannot use spaceship
Could you add 3 testcases for this new logic? The code was out of my head and in no way tested.

```
null => DateInterval
DateInterval#1 => DateInterval#2
DateInterval => null
```

2021-04-27 09:02 UTC, Gummibeer commented
@nagi1 can you take care of that?

2021-04-27 09:03 UTC, nagi1 commented
Will do, Can you give me example use case to work with?

2021-04-27 09:22 UTC, Gummibeer commented
A new attribute with, I think, custom object cast to DateInterval instance.
And a testcase covering at least the three listed scenarios.

`$model->interval = CarbonInterval::minute()` for example.

2021-04-27 10:53 UTC, nagi1 commented
@Gummibeer You may merge this now :)

2021-04-27 11:09 UTC, Gummibeer requested changes

2021-04-27 11:09 UTC, Gummibeer commented on src/Traits/LogsActivity.php
> +                        return intval(! CarbonInterval::make($old)->equalTo($new));
Could you use something like `CarbonInterval::make($old)->equalTo($new) ? 0 : 1` - the current one is correct but not really readable.

2021-04-27 11:21 UTC, merged